[funfacts]
title = "Wikipedia — did you know?"
url = "https://en.wikipedia.org/wiki/Main_Page"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"

[kkj]
title = "快科技"
url = "https://www.mydrivers.com/"
entrySelector = ".newslist > li"
titleSelector = "span"
linkSelector = "span a"
