[funfacts]
title = "Wikipedia — did you know?"
url = "https://en.wikipedia.org/wiki/Main_Page"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"

[kkj]
title = "快科技"
url = "https://www.mydrivers.com/"
entrySelector = "#newlist_3_1 > h5 a"
titleSelector = "#newlist_3_1 > h5 a"
linkSelector = "#newlist_3_1 > h5 a"
contentSelector = "#newlist_3_1 > .phhot_lb_right"
